import { z } from 'zod';

export const createHomestaySchema = z.object({
  body: z.object({
    name: z.string().min(1, 'Name is required'),
    slug: z.string().min(1, 'Slug is required'),
    description: z.string().optional(),
    location: z.string().min(1, 'Location is required'),
    address: z.string().optional(),
    lat: z.number().optional(),
    lng: z.number().optional(),
    price_per_night: z.number().nonnegative(),
    weekend_price: z.number().nonnegative().optional(),
    max_guests: z.number().int().positive(),
    amenities: z.array(z.string()),
    images: z.array(z.string().url()).optional(),
    cover_image_url: z.string().url().optional().or(z.literal('')),
    badge: z.string().optional(),
    avg_rating: z.number().min(0).max(5).optional(),
    review_count: z.number().int().nonnegative().optional(),
    is_available: z.boolean().default(true),
    is_published: z.boolean().default(true),
    room_images: z.object({
      room: z.array(z.string().url()).optional(),
      lobby: z.array(z.string().url()).optional(),
      entrance: z.array(z.string().url()).optional(),
      reception: z.array(z.string().url()).optional(),
      public_area: z.array(z.string().url()).optional(),
    }).optional(),
    exact_location: z.string().optional(),
    map_location_url: z.string().optional(),
    room_type: z.string().optional(),
    rules_and_policies: z.string().optional(),
    checkin_time: z.string().optional(),
    checkout_time: z.string().optional(),
    max_adults: z.number().int().nonnegative().optional(),
    max_children: z.number().int().nonnegative().optional(),
    bed_type: z.string().optional(),
    ac_type: z.string().optional(),
    number_of_rooms: z.number().int().positive().optional(),
  })
});

export const updateHomestaySchema = z.object({
  body: z.object({
    name: z.string().optional(),
    slug: z.string().optional(),
    description: z.string().optional(),
    location: z.string().optional(),
    address: z.string().optional(),
    lat: z.number().optional(),
    lng: z.number().optional(),
    price_per_night: z.number().nonnegative().optional(),
    weekend_price: z.number().nonnegative().optional(),
    max_guests: z.number().int().positive().optional(),
    amenities: z.array(z.string()).optional(),
    images: z.array(z.string().url()).optional(),
    cover_image_url: z.string().url().optional().or(z.literal('')),
    badge: z.string().optional(),
    avg_rating: z.number().min(0).max(5).optional(),
    review_count: z.number().int().nonnegative().optional(),
    is_available: z.boolean().optional(),
    is_published: z.boolean().optional(),
    room_images: z.object({
      room: z.array(z.string().url()).optional(),
      lobby: z.array(z.string().url()).optional(),
      entrance: z.array(z.string().url()).optional(),
      reception: z.array(z.string().url()).optional(),
      public_area: z.array(z.string().url()).optional(),
    }).optional(),
    exact_location: z.string().optional(),
    map_location_url: z.string().optional(),
    room_type: z.string().optional(),
    rules_and_policies: z.string().optional(),
    checkin_time: z.string().optional(),
    checkout_time: z.string().optional(),
    max_adults: z.number().int().nonnegative().optional(),
    max_children: z.number().int().nonnegative().optional(),
    bed_type: z.string().optional(),
    ac_type: z.string().optional(),
    number_of_rooms: z.number().int().positive().optional(),
  })
});
